<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mira-base">

  <xacro:property name="width" value="0.2" />
  <xacro:property name="leglen" value="0.01" />
  <xacro:property name="baselen" value="0.2" />
  <xacro:property name="wheeldiam" value="0.1" />
  <xacro:property name="pi" value="3.1415" />
    <xacro:macro name="mira-base" params="*origin parent:=base_link name:=mira-base"/>

  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>

  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
      <!-- <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" /> -->
    </inertial>
  </xacro:macro>

<xacro:macro name="default_inertial_wheels">
    <inertial>
    <mass value="0.5" />
    <origin xyz="0 0 0" rpy="${pi/2} 0 0" /> 
        <inertia ixx="${(0.5 * (3.0*0.05*0.05 + 0.02*0.02)) / 12.0}" ixy="0" ixz="0"
        iyy="${(0.5 * (3.0*0.05*0.05 + 0.02*0.02)) / 12.0}" iyz="0"
        izz="${0.5 * 0.5 * (0.05*0.05)}"/>
    </inertial>
    <!-- <inertia ixx="${(0.5 * (3.0*0.05*0.05 + 0.02*0.02)) / 12.0}" ixy="0" ixz="0"
        iyy="${0.5 * 0.5 * (0.05*0.05)}" iyz="0"
        izz="${(0.5 * (3.0*0.05*0.05 + 0.02*0.02)) / 12.0}"/>
    </inertial> -->
</xacro:macro>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.27 0.17 0.08" />
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.27 0.17 0.08" />
      </geometry>
    </collision>
    <xacro:default_inertial mass="6"/>
  </link>

  <xacro:macro name="wheel" params="prefix suffix reflect">

    <link name="${prefix}_${suffix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${wheeldiam/2}" length="0.04"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${wheeldiam/2}" length="0.04"/>
        </geometry>
      </collision>
      <!-- <xacro:default_inertial mass="1"/> -->
      <xacro:default_inertial_wheels/>
    </link>
    <joint name="${prefix}_${suffix}_wheel_joint" type="continuous">
      <axis xyz="0 1 0" rpy="0 0 0" />
      <parent link="${prefix}_base"/>
      <child link="${prefix}_${suffix}_wheel"/>
      <!-- <origin xyz="${baselen*reflect/4} 0 -0.001" rpy="0 0 0"/> -->
      <origin xyz="${reflect*0.125 } 0 -0.001" rpy="0 0 0"/>
    </joint>

    <!-- This block provides the simulator (Gazebo) with information on a few additional
    physical properties. See http://gazebosim.org/tutorials/?tut=ros_urdf for more-->
    <gazebo reference="${prefix}_${suffix}_wheel">
      <mu1 value="200.0"/>
      <mu2 value="100.0"/>
      <kp value="10000000.0" />
      <kd value="1.0" />
      <selfCollide value="false"/>
      <material>Gazebo/Grey</material>
    </gazebo>

    <!-- This block connects the wheel joint to an actuator (motor), which informs both
    simulation and visualization of the robot -->
    <transmission name="${prefix}_${suffix}_wheel_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="${prefix}_${suffix}_wheel_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="${prefix}_${suffix}_wheel_joint">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
      </joint>
    </transmission>

  </xacro:macro>

  <xacro:macro name="leg" params="prefix reflect">
    <link name="${prefix}_leg">
      <visual>
        <geometry>
          <box size="${leglen} 0.04 0.01"/>
        </geometry>
        <origin xyz="0 0 -${leglen/2}" rpy="0 ${pi/2} 0"/>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <box size="${leglen} 0.04 0.01"/>
        </geometry>
        <origin xyz="0 0 ${leglen/2}" rpy="0 ${pi/2} 0"/>
      </collision>
      <xacro:default_inertial mass="0.5"/>
    </link>

    <joint name="base_to_${prefix}_leg" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_leg"/>
      <origin xyz="0 ${reflect*(width/2)} 0." />
    </joint>

    <link name="${prefix}_base">
      <visual>
        <geometry>
          <box size="${baselen} 0.04 0.095"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <box size="${baselen} 0.04 0.095"/>
        </geometry>
      </collision>
      <xacro:default_inertial mass="0.5"/>
    </link>

    <joint name="${prefix}_base_joint" type="fixed">
      <parent link="${prefix}_leg"/>
      <child link="${prefix}_base"/>
      <origin xyz="0 0 0" />
    </joint>
    <xacro:wheel prefix="${prefix}" suffix="front" reflect="1"/>
    <xacro:wheel prefix="${prefix}" suffix="back" reflect="-1"/>
  </xacro:macro>
  <xacro:leg prefix="right" reflect="-1" />
  <xacro:leg prefix="left" reflect="1" />
</robot>